---
title: 'Facilitator Assessment'
author: "Josephine McKelvy"
date: "July 14, 2021"
output:
  html_document:
    df_print: paged
subtitle: Summarizing Data by Group
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Facilitator Competency Assessment
```{r}
rawfac.df <- read.csv("AYC Program Facilitator Competency Assessment.csv", stringsAsFactors = TRUE)
fac.df <- rawfac.df[2:nrow(rawfac.df),c(10:12,21:80)] #97 variables
fac.df$Today.s.Date <- as.Date(fac.df$Today.s.Date, "%m/%d/%Y") 

capable <- fac.df[fac.df$Today.s.Date >= "2020-07-01" & fac.df$Today.s.Date <= "2021-06-30", c(8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,44,46,48,50,52,54,56,58,60,62)]
comfort <- fac.df[fac.df$Today.s.Date >= "2020-07-01" & fac.df$Today.s.Date <= "2021-06-30", c(9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,45,47,49,51,53,55,57,59,61,63)]
names(capable) <- c("Menstrual",
                  "Types of Sex",
                  "Contraception",
                  "Condom Use",
                  "STI transmission",
                  "STI effects",
                  "STI treatment",
                  "Biological sex",
                  "Gender norms",
                  "Sexual orientation",
                  "Relationships",
                  "Consent laws",
                  "(skill) Coercion",
                  "(skill) Role play",
                  "(skill) Slang terms",
                  "(skill) challenging behavior",
                  "(skill) Acceptance",
                  #"(skill) Trauma Triggers",
                  "(skill) Disclosures",
                  "(skill) Values neutral",
                  "(skill) Respond",
                  "(skill) Refer",
                  "(skill) Resources",
                  "(TIA) Interactions",
                  "(TIA) Triggers",
                  "(TIA) Communication",
                  "(TIA) Relationships",
                  "(TIA) ACES")

names(comfort) <- c("Menstrual",
                  "Types of Sex",
                  "Contraception",
                  "Condom Use",
                  "STI transmission",
                  "STI effects",
                  "STI treatment",
                  "Biological sex",
                  "Gender norms",
                  "Sexual orientation",
                  "Relationships",
                  "Consent laws",
                  "(skill) Coercion",
                  "(skill) Role play",
                  "(skill) Slang terms",
                  "(skill) challenging behavior",
                  "(skill) Acceptance",
                  #"(skill) Trauma Triggers",
                  "(skill) Disclosures",
                  "(skill) Values neutral",
                  "(skill) Respond",
                  "(skill) Refer",
                  "(skill) Resources",
                  "(TIA) Interactions",
                  "(TIA) Triggers",
                  "(TIA) Communication",
                  "(TIA) Relationships",
                  "(TIA) ACES")

capable$type <- 1
comfort$type <- 2
combined <- rbind(capable,comfort)

combined$type <- factor(combined$type,
                   levels = c(1,2),
                   labels = c("capable","comfort"))

labelskill <- c("Not sure",
                "Low",
                "Moderate",
                "High")

combined$`Menstrual` <- factor(combined$`Menstrual`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Types of Sex` <- factor(combined$`Types of Sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Contraception` <- factor(combined$`Contraception`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Condom Use` <- factor(combined$`Condom Use`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`STI transmission` <- factor(combined$`STI transmission`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`STI effects` <- factor(combined$`STI effects`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`STI treatment` <- factor(combined$`STI treatment`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Biological sex` <- factor(combined$`Biological sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Gender norms` <- factor(combined$`Gender norms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Sexual orientation` <- factor(combined$`Sexual orientation`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Relationships` <- factor(combined$`Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`Consent laws` <- factor(combined$`Consent laws`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Coercion` <- factor(combined$`(skill) Coercion`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Role play` <- factor(combined$`(skill) Role play`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Slang terms` <- factor(combined$`(skill) Slang terms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) challenging behavior` <- factor(combined$`(skill) challenging behavior`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Acceptance` <- factor(combined$`(skill) Acceptance`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
#combined$`(skill) Trauma Triggers` <- factor(combined$`(skill) Trauma Triggers`,
#                               levels = c(4,3,2,1),
#                               labels = labelskill,
#                               ordered = TRUE)
combined$`(skill) Disclosures` <- factor(combined$`(skill) Disclosures`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Values neutral` <- factor(combined$`(skill) Values neutral`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Respond` <- factor(combined$`(skill) Respond`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Refer` <- factor(combined$`(skill) Refer`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(skill) Resources` <- factor(combined$`(skill) Resources`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(TIA) Interactions` <- factor(combined$`(TIA) Interactions`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(TIA) Triggers` <- factor(combined$`(TIA) Triggers`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(TIA) Communication` <- factor(combined$`(TIA) Communication`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(TIA) Relationships` <- factor(combined$`(TIA) Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
combined$`(TIA) ACES` <- factor(combined$`(TIA) ACES`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
############
# Optional #
############

names(fac.df) <- c("First Name","Last Name","IO","Email","Phone","Date","First Time",
                  "Capable: Menstrual",                   "Comfort: Menstrual",
                  "Capable: Types of Sex",                "Comfort: Types of Sex",
                  "Capable: Contraception",               "Comfort: Contraception",
                  "Capable: Condom Use",                  "Comfort: Condom Use",
                  "Capable: STI transmission",            "Comfort: STIs transmission",
                  "Capable: STI effects",                 "Comfort: STI effects",
                  "Capable: STI treatment",               "Comfort: STI treatment",
                  "Capable: Biological sex",              "Comfort: Biological sex",
                  "Capable: Gender norms",                "Comfort: Gender norms",
                  "Capable: Sexual orientation",          "Comfort: Sexual orientation",
                  "Capable: Relationships",               "Comfort: Relationships",
                  "Capable: Consent laws",                "Comfort: Consent laws",
                  "Capable: (skill) Coercion",            "Comfort: (skill) Coercion",
                  "Capable: (skill) Role play",           "Comfort: (skill) Role play",
                  "Capable: (skill) Slang terms",         "Comfort: (skill) Slang terms",
                  "Capable: (skill) challenging behavior","Comfort: (skill) challenging behavior",
                  "Capable: (skill) Acceptance",          "Comfort: (skill) Acceptance",
                  "Capable: (skill) Trauma Triggers",     "Comfort: (skill) Trauma Triggers",
                  "Capable: (skill) Disclosures",         "Comfort: (skill) Disclosures",
                  "Capable: (skill) Values neutral",      "Comfort: (skill) Values neutral",
                  "Capable: (skill) Respond",             "Comfort: (skill) Respond",
                  "Capable: (skill) Refer",               "Comfort: (skill) Refer",
                  "Capable: (skill) Resources",           "Comfort: (skill) Resources",
                  "Capable: (TIA) Interactions",          "Comfort: (TIA) Interactions",
                  "Capable: (TIA) Triggers",              "Comfort: (TIA) Triggers",
                  "Capable: (TIA) Communication",         "Comfort: (TIA) Communication",
                  "Capable: (TIA) Relationships",         "Comfort: (TIA) Relationships",
                  "Capable: (TIA) ACES",                  "Comfort: (TIA) ACES")

fac.df[fac.df==""] <- NA

fac.df$IO <- factor(fac.df$IO,
                    levels = c(1,2,3,4,5,6,7,8,9),
                    labels = c("Alamance Achieves","ACDSS","ACHD","DreamCenter","CrossRoads","Elon","Exchange Club","PAYC","SABGC"))

fac.df$Date <- as.Date(fac.df$Date, "%m/%d/%Y") 

fac.df$`First Time` <- factor(fac.df$`First Time`,
                    levels = c(1,2),
                    labels = c("Yes", "No"))

fac.df$`Menstrual` <- factor(fac.df$`Menstrual`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Menstrual` <- factor(fac.df$`Comfort: Menstrual`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Types of Sex` <- factor(fac.df$`Types of Sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Types of Sex` <- factor(fac.df$`Comfort: Types of Sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Contraception` <- factor(fac.df$`Contraception`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Contraception` <- factor(fac.df$`Comfort: Contraception`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Condom Use` <- factor(fac.df$`Condom Use`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Condom Use` <- factor(fac.df$`Comfort: Condom Use`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`STI transmission` <- factor(fac.df$`STI transmission`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: STIs transmission` <- factor(fac.df$`Comfort: STIs transmission`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`STI effects` <- factor(fac.df$`STI effects`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: STI effects` <- factor(fac.df$`Comfort: STI effects`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`STI treatment` <- factor(fac.df$`STI treatment`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: STI treatment` <- factor(fac.df$`Comfort: STI treatment`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Biological sex` <- factor(fac.df$`Biological sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Biological sex` <- factor(fac.df$`Comfort: Biological sex`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Gender norms` <- factor(fac.df$`Gender norms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Gender norms` <- factor(fac.df$`Comfort: Gender norms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Sexual orientation` <- factor(fac.df$`Sexual orientation`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Sexual orientation` <- factor(fac.df$`Comfort: Sexual orientation`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Relationships` <- factor(fac.df$`Capable: Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Relationships` <- factor(fac.df$`Comfort: Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: Consent laws` <- factor(fac.df$`Capable: Consent laws`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: Consent laws` <- factor(fac.df$`Comfort: Consent laws`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Coercion` <- factor(fac.df$`Capable: (skill) Coercion`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Coercion` <- factor(fac.df$`Comfort: (skill) Coercion`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Role play` <- factor(fac.df$`Capable: (skill) Role play`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Role play` <- factor(fac.df$`Comfort: (skill) Role play`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Slang terms` <- factor(fac.df$`Capable: (skill) Slang terms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Slang terms` <- factor(fac.df$`Comfort: (skill) Slang terms`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) challenging behavior` <- factor(fac.df$`Capable: (skill) challenging behavior`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) challenging behavior` <- factor(fac.df$`Comfort: (skill) challenging behavior`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Acceptance` <- factor(fac.df$`Capable: (skill) Acceptance`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Acceptance` <- factor(fac.df$`Comfort: (skill) Acceptance`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Trauma Triggers` <- factor(fac.df$`Capable: (skill) Trauma Triggers`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Trauma Triggers` <- factor(fac.df$`Comfort: (skill) Trauma Triggers`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Disclosures` <- factor(fac.df$`Capable: (skill) Disclosures`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Disclosures` <- factor(fac.df$`Comfort: (skill) Disclosures`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Values neutral` <- factor(fac.df$`Capable: (skill) Values neutral`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Values neutral` <- factor(fac.df$`Comfort: (skill) Values neutral`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Respond` <- factor(fac.df$`Capable: (skill) Respond`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Respond` <- factor(fac.df$`Comfort: (skill) Respond`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Refer` <- factor(fac.df$`Capable: (skill) Refer`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Refer` <- factor(fac.df$`Comfort: (skill) Refer`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (skill) Resources` <- factor(fac.df$`Capable: (skill) Resources`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (skill) Resources` <- factor(fac.df$`Comfort: (skill) Resources`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (TIA) Interactions` <- factor(fac.df$`Capable: (TIA) Interactions`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (TIA) Interactions` <- factor(fac.df$`Comfort: (TIA) Interactions`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (TIA) Triggers` <- factor(fac.df$`Capable: (TIA) Triggers`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (TIA) Triggers` <- factor(fac.df$`Comfort: (TIA) Triggers`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (TIA) Communication` <- factor(fac.df$`Capable: (TIA) Communication`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (TIA) Communication` <- factor(fac.df$`Comfort: (TIA) Communication`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (TIA) Relationships` <- factor(fac.df$`Capable: (TIA) Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (TIA) Relationships` <- factor(fac.df$`Comfort: (TIA) Relationships`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Capable: (TIA) ACES` <- factor(fac.df$`Capable: (TIA) ACES`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
fac.df$`Comfort: (TIA) ACES` <- factor(fac.df$`Comfort: (TIA) ACES`,
                               levels = c(4,3,2,1),
                               labels = labelskill,
                               ordered = TRUE)
############

library(likert)

combined <- na.omit(combined) 

combinedlkt <- likert(items=combined[,1:27], grouping = combined$type)
plot(combinedlkt, positive.order = TRUE) + ggtitle("Facilitators' Capability & Comfort Levels")
ggsave("Facilitators Assessment.png", width = 9, height = 20)

lkt1 <- likert(items=combined[,1:12], grouping = combined$type)
plot(lkt1, positive.order = TRUE) + ggtitle("Facilitators' Capability & Comfort Levels: Topics of Sexual Health")
ggsave("Facilitators Assessment-topics.png", width = 9, height = 10)

lkt2 <- likert(items=combined[,13:22], grouping = combined$type)
plot(lkt2, positive.order = TRUE) + ggtitle("Facilitators' Capability & Comfort Levels: Facilitation Skills")
ggsave("Facilitators Assessment-skills.png", width = 9, height = 8)

lkt3 <- likert(items=combined[,23:27], grouping = combined$type)
plot(lkt3, positive.order = TRUE) + ggtitle("Facilitators' Capability & Comfort Levels: Trauma-Informed Approaches")
ggsave("Facilitators Assessment-TIA.png", width = 9, height = 5)
```
